// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq2oTiY1_-LDB72hdTzFejZ68WH7YbwM0',
    appId: '1:525268134920:android:af5a42a8f484064317b5bd',
    messagingSenderId: '525268134920',
    projectId: 'baato-eb4ff',
    storageBucket: 'baato-eb4ff.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1KCjDK0ftG2keM8VI_v8278SLQuVw-2I',
    appId: '1:525268134920:web:d460bfc25a46c47c17b5bd',
    messagingSenderId: '525268134920',
    projectId: 'baato-eb4ff',
    authDomain: 'baato-eb4ff.firebaseapp.com',
    storageBucket: 'baato-eb4ff.firebasestorage.app',
    measurementId: 'G-C94YYGF3Z0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQto9jhtamIGBTiiju_xWbQPwgwl-__GQ',
    appId: '1:525268134920:ios:c761f7271148799517b5bd',
    messagingSenderId: '525268134920',
    projectId: 'baato-eb4ff',
    storageBucket: 'baato-eb4ff.firebasestorage.app',
    iosBundleId: 'com.example.baato',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQto9jhtamIGBTiiju_xWbQPwgwl-__GQ',
    appId: '1:525268134920:ios:c761f7271148799517b5bd',
    messagingSenderId: '525268134920',
    projectId: 'baato-eb4ff',
    storageBucket: 'baato-eb4ff.firebasestorage.app',
    iosBundleId: 'com.example.baato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1KCjDK0ftG2keM8VI_v8278SLQuVw-2I',
    appId: '1:525268134920:web:1193ce26849a805a17b5bd',
    messagingSenderId: '525268134920',
    projectId: 'baato-eb4ff',
    authDomain: 'baato-eb4ff.firebaseapp.com',
    storageBucket: 'baato-eb4ff.firebasestorage.app',
    measurementId: 'G-HV5SY3N6XL',
  );

}